name: sekolator
description: "sekolator"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true